package com.joaoeoneves.fintrack.ui.theme

import androidx.compose.ui.graphics.Color

// Deep jade/emerald palette — light scheme
val LightPrimary = Color(0xFF146C43)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFA6F2C6)
val LightOnPrimaryContainer = Color(0xFF00210F)
val LightSecondary = Color(0xFF4C6358)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCEE9D9)
val LightOnSecondaryContainer = Color(0xFF092016)
val LightTertiary = Color(0xFF3D6373)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFC1E8FB)
val LightOnTertiaryContainer = Color(0xFF001F29)
val LightBackground = Color(0xFFF7FBF5)
val LightOnBackground = Color(0xFF191C1A)
val LightSurface = Color(0xFFF7FBF5)
val LightOnSurface = Color(0xFF191C1A)
val LightSurfaceVariant = Color(0xFFDCE5DD)
val LightOnSurfaceVariant = Color(0xFF414942)
val LightOutline = Color(0xFF717971)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

// Deep jade/emerald palette — dark scheme (proper M3 tonal dark palette, not a lightness flip)
val DarkPrimary = Color(0xFF8BD5A9)
val DarkOnPrimary = Color(0xFF00391D)
val DarkPrimaryContainer = Color(0xFF00522C)
val DarkOnPrimaryContainer = Color(0xFFA6F2C6)
val DarkSecondary = Color(0xFFB2CCBD)
val DarkOnSecondary = Color(0xFF1E352A)
val DarkSecondaryContainer = Color(0xFF354B40)
val DarkOnSecondaryContainer = Color(0xFFCEE9D9)
val DarkTertiary = Color(0xFFA5CCDE)
val DarkOnTertiary = Color(0xFF053543)
val DarkTertiaryContainer = Color(0xFF244C5B)
val DarkOnTertiaryContainer = Color(0xFFC1E8FB)
val DarkBackground = Color(0xFF10140F)
val DarkOnBackground = Color(0xFFE1E3DE)
val DarkSurface = Color(0xFF10140F)
val DarkOnSurface = Color(0xFFE1E3DE)
val DarkSurfaceVariant = Color(0xFF414942)
val DarkOnSurfaceVariant = Color(0xFFC0C9C1)
val DarkOutline = Color(0xFF8A938B)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
